wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1641747298
    t:
      1:
      - 1
      3:
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
batch_size:
  desc: null
  value: 30
dropout_attn:
  desc: null
  value: 0.11750396206284588
dropout_rate:
  desc: null
  value: 0.22961699020986656
embed_dim:
  desc: null
  value: 303
learning_rate:
  desc: null
  value: 0.0005267908639863879
num_epochs:
  desc: null
  value: 30
patch_size:
  desc: null
  value: 7
