name: "Deploy"
on:
  push:
    branches: [master]

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - name: DVC Pull
        run: dvc pull fit_model
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: Configure Docker auth
        run: gcloud auth configure-docker --quiet eu-west4-docker.pkg.dev
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{github.sha}}
          cache-from: type=registry,ref=europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{github.sha}}
          cache-to: type=inline
      # - name: Build and push
      #   run: |
      #     docker build -t europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{ github.sha }} .
      #     docker push europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{ github.sha }}
      - run: |
          gcloud ai models upload \
            --container-image-uri=europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{github.sha}} \
            --display-name=masks-${{ github.sha }}
            --container-ports=[7080]
            --container-health-route=/ping
            --container-predict-route=/predictions/masks
