name: "Deploy"
on:
  push:
    branches: [master]

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: Configure Docker auth
        run: gcloud auth configure-docker --quiet europe-west4-docker.pkg.dev
      - name: DVC Pull
        run: dvc pull fit_model
      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build and push
        run: |
          docker build -t europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{ github.sha }} .
          docker push europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{ github.sha }}
      - run: |
          gcloud ai models upload \
            --container-image-uri=europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{github.sha}} \
            --display-name=masks-${{ github.sha }} \
            --container-ports=7080 \
            --container-health-route=/ping \
            --region=europe-west4 \
            --project=dtumlops-project-mask-no-mask \
            --container-predict-route=/predictions/masks

          MODEL_ID=$(gcloud ai models list \
            --region=europe-west4 \
            --project=dtumlops-project-mask-no-mask \
            --filter=displayName:masks-${{ github.sha }} \
            --format="value(name)" | sed -rn 's/.*\/models\/([0-9]+)/\1/p')

          gcloud ai endpoints deploy-model 379938442001252352 \
            --region=europe-west4 \
            --model=$MODEL_ID \
            --display-name=masks \
            --machine-type=n1-standard-2 \
            --min-replica-count=1 \
            --project=dtumlops-project-mask-no-mask \  
            --max-replica-count=2 \
            --traffic-split=0=100
