name: "Deploy"
on:
  push:
    branches: [master]

jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-dvc@v1
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - run: gcloud auth configure-docker --quiet eu-west4-docker.pkg.dev
      - name: Build and push
        run: |
          dvc pull fit_model
          docker build -t europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{ github.sha }} .
          docker push europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{ github.sha }}
      - run: |
          gcloud ai models upload \
            --container-image-uri=europe-west4-docker.pkg.dev/dtumlops-project-mask-no-mask/dtu-mlops/serve:${{github.sha}} \
            --display-name=masks-${{ github.sha }}
            --container-ports=[7080]
            --container-health-route=/ping
            --container-predict-route=/predictions/masks
