name: "Evaluate"
on:
  pull_request:
    types: [opened, reopened]
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on GCP
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          cml runner \
              --name=trainer \
              --cloud=gcp \
              --cloud-region=eu-west \
              --cloud-type=e2-standard-2 \
              --cloud-spot \
              --labels=cml-gpu \
              --reuse \
              --idle-timeout=900
  train-model:
    needs: deploy-runner
    runs-on: [self-hosted, cml-gpu]
    timeout-minutes: 120
    container:
      image: docker://iterativeai/cml:0-dvc2-base1 #-gpu
      # options: --gpus all
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: "pip"
          cache-dependency-path: requirements/dev.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          dvc pull
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md master > report.md
          cml-send-comment report.md

  # build:
  #   runs-on: ubuntu-latest
  #   container: docker://ghcr.io/iterative/cml:0-dvc2-base1
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.8
  #       cache: 'pip'
  #       cache-dependency-path: requirements/dev.txt
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements/dev.txt
  #   - name: Test with pytest
  #     run: |
  #       pip install pytest
  #       pytest
  #   - id: 'auth'
  #     uses: 'google-github-actions/auth@v0'
  #     with:
  #       credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
  #   - name: Pull data/cached steps
  #     run: |
  #       dvc update data/*.dvc
  #       dvc pull
  #   - name: Run pipeline
  #     run: |
  #       dvc repro
